name: lint

on: push

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: nf-core/nf-core-gh-action@master
        with:
          nextflow_version: '20.04.1'
          nfcore_version: '1.9'
